[package]
name = "bevy_mover"
version = "0.1.0"
edition = "2021"

[target.'cfg(target_arch = "wasm32")'.dependencies]
bevy = { version = "0.13", default-features = false, features = ["webgl2"] }

[dependencies]
bevy = "0.13"

[dependencies.uuid]
version = "1.3"
features = ["js"]